import assert from 'node:assert/strict';
import { test } from 'vitest';
import { mathIslands } from './math-islands';
import { ReviewMathCodec } from './review-math-codec';
const m = '<span class="katex"><span class="katex-mathml"><math><mi>x</mi></math></span><span>x</span></span>';
test('balanced nested math', () => assert.deepEqual(mathIslands('<p>a'+m+'b</p>'), [{start:4,end:4+m.length,html:m}]));
test('not katex-html/display', () => assert.equal(mathIslands('<span class="katex-html">x</span>')!.length,0));
test('quoted angle brackets', () => assert.equal(mathIslands(m.replace('<span>x', '<span title="a > b">x'))!.length,1));
test('not a class inside an attribute', () => assert.equal(mathIslands("<span title='class=\"katex\"'>x</span>")!.length,0));
test('comments are inert', () => assert.equal(mathIslands('<!--'+m+'-->')!.length,0));
test('raw text fallback', () => assert.equal(mathIslands('<script>'+m+'</script>'),null));
test('malformed fallback', () => assert.equal(mathIslands('<span class="katex"><b>x</span>'),null));
test('source metadata kept in row analysis', () => assert.equal(mathIslands(m.replace('<mi>', '<mi data-source-line="7">'))!.length,0));
test('exact roundtrip', () => { const c=new ReviewMathCodec(); const p=c.pack('<p>'+m+m+'</p>'); assert.equal(p!.restore(p!.html), '<p>'+m+m+'</p>'); assert.equal(c.entryCount,1); });
test('stable identity', () => { const c=new ReviewMathCodec(); assert.equal(c.pack(m)!.html,c.pack(m)!.html); });
test('changed output is new identity', () => { const c=new ReviewMathCodec(); assert.notEqual(c.pack(m)!.html,c.pack(m.replace('<mi>x','<mi>y'))!.html); });
test('bounded eviction never aliases', () => { const c=new ReviewMathCodec(100000,1); const p=c.pack(m); c.pack(m.replace('<mi>x','<mi>y')); assert.notEqual(c.pack(m)!.html,p!.html); assert.equal(p!.restore(p!.html),m); assert.equal(c.entryCount,1); });
test('oversize transient identity still restores repeated occurrences', () => { const c=new ReviewMathCodec(0,0); const p=c.pack(m+m); assert.equal(p!.restore(p!.html),m+m); assert.equal(c.retainedBytes,0); });
test('authored token bypass', () => assert.equal(new ReviewMathCodec().pack('<span data-setdown-opaque-math="m1"></span>'),null));
test('unknown internal token rejected', () => { const p=new ReviewMathCodec().pack(m); assert.throws(()=>p!.restore('<span class="katex" data-setdown-opaque-math="m999"></span>')); });
