import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { _electron as electron, expect, test } from '@playwright/test';
import { disposeApplication, focusApplication } from './electron-app';
import { previews } from './preview-view';

const exec = promisify(execFile);
test('Graph resizes, refreshes and opens immutable Markdown revisions in existing review', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'setdown-history-'));
  const configRoot = await mkdtemp(path.join(os.tmpdir(), 'setdown-history-config-'));
  const file = path.join(root, 'note.md');
  const git = (...args: string[]) => exec('git', args, { cwd: root });
  let app: Awaited<ReturnType<typeof electron.launch>> | undefined;
  try {
    await git('init', '-b', 'main');
    await git('config', 'user.name', 'History Test');
    await git('config', 'user.email', 'history@example.test');
    await writeFile(file, '# First revision\n\n$$x^2$$\n');
    await git('add', '.'); await git('commit', '-m', 'Initial document');
    const first = (await git('rev-parse', 'HEAD')).stdout.trim();
    await writeFile(file, '# Second revision\n\n$$x^2 + y^2$$\n');
    await git('commit', '-am', 'Revise document');
    const second = (await git('rev-parse', 'HEAD')).stdout.trim();
    await writeFile(file, '# Working document\n');
    const { ELECTRON_RUN_AS_NODE: _ignored, ...env } = process.env;
    app = await electron.launch({ args: ['.'], env: { ...env, XDG_CONFIG_HOME: configRoot } });
    const window = await app.firstWindow();
    const errors: string[] = [];
    window.on('pageerror', (error) => errors.push(error.message));
    await window.evaluate(async (folder) => {
      await (window as unknown as { marktex: { restoreProjectFolder(root: string): Promise<unknown> } }).marktex.restoreProjectFolder(folder);
    }, root);
    await Promise.all([window.waitForEvent('load'), window.reload()]);
    await focusApplication(app);
    await window.getByRole('button', { name: 'Toggle Folder Tools' }).click();
    await window.getByRole('button', { name: 'Source Control', exact: true }).click();
    const graph = window.locator('web-git-graph');
    await expect(graph.locator('.row')).toHaveCount(2);
    const pane = window.getByRole('region', { name: 'Git history', exact: true });
    const separator = window.getByRole('button', { name: 'Resize Git Graph' });
    const before = (await pane.boundingBox())!;
    const handle = (await separator.boundingBox())!;
    await window.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
    await window.mouse.down(); await window.mouse.move(handle.x + handle.width / 2, handle.y - 65, { steps: 6 }); await window.mouse.up();
    expect((await pane.boundingBox())!.height).toBeGreaterThan(before.height + 40);
    await separator.press('ArrowDown');
    const toggle = pane.getByRole('button', { name: 'Graph', exact: true });
    await toggle.click(); await expect(graph).toHaveCount(0);
    await toggle.click(); await expect(graph.locator('.row')).toHaveCount(2);
    await graph.locator(`.row[data-oid="${second}"]`).click();
    await graph.locator('.tree-file').click();
    const modified = window.locator('.modified-in-monaco-diff-editor');
    await expect(modified.locator('.view-lines')).toContainText('Second revision');
    await expect(window.locator('.original-in-monaco-diff-editor .view-lines')).toContainText('First revision');
    await expect(window.locator('.git-diff-tab')).toContainText(second.slice(0, 8));
    await window.screenshot({ path: test.info().outputPath('git-history.png') });
    await modified.getByRole('textbox').press('Control+End');
    await modified.getByRole('textbox').pressSequentially('MUST NOT EDIT');
    await expect(modified.locator('.view-lines')).not.toContainText('MUST NOT EDIT');
    expect(await readFile(file, 'utf8')).toBe('# Working document\n');
    await window.getByRole('button', { name: 'View Rendered Diff' }).click();
    await expect.poll(async () => ({ visible: await previews(app!).hasVisible(), error: await window.locator('.project-error').allTextContents() })).toEqual({ visible: true, error: [] });
    await expect.poll(() => previews(app!).evaluate<string>('document.body.textContent')).toContain('Second revision');
    await window.getByRole('button', { name: 'View Source Diff' }).click();
    await graph.locator(`.row[data-oid="${first}"]`).click();
    await graph.locator('.tree-file').click();
    await expect(modified.locator('.view-lines')).toContainText('First revision');
    await expect(window.locator('.git-diff-tab')).toHaveCount(2);
    await graph.getByRole('treegrid').press('Escape');
    await expect(window.getByRole('button', { name: 'View Rendered Diff' })).toBeVisible();
    await git('commit', '-am', 'External commit');
    await expect(graph.locator('.row').filter({ hasText: 'External commit' })).toHaveCount(1);
    // An immutable review keeps its content when the local branch changes.
    await expect(modified.locator('.view-lines')).toContainText('First revision');
    const height = (await pane.boundingBox())!.height;
    await Promise.all([window.waitForEvent('load'), window.reload()]);
    await expect(graph.locator('.row')).toHaveCount(3);
    await expect(modified.locator('.view-lines')).toContainText('First revision');
    expect(Math.abs((await pane.boundingBox())!.height - height)).toBeLessThan(2);
    expect(errors).toEqual([]);
  } finally {
    if (app) await disposeApplication(app);
    await rm(root, { recursive: true, force: true });
    await rm(configRoot, { recursive: true, force: true });
  }
});
